### PR TITLE
test: Fix tests on Java 21 or newer; replace InetAddress mocking code

### LINKED ISSUE #144: InetAddress mocking breaks java21 builds
Since recent changes in java 21,  InetAddress is declared a sealed class. Thus, mocking of InetAddress is no longer possible. As a result, some unit tests can't be compiled

### PR DESCRIPTION
**Pull request by kohlschuetter**
Some unit tests work with fake ("mocked") InetAddress objects, which are currently assembled via mockito. With Java 21 and newer, this is no longer possible.

Replace the mocking code with a new "InetAddressMockery" class that can provide real Inet4Address objects by means of Java object deserialization.

Fixes #144

### CODE REVIEW

File: core/src/test/java/org/dcache/testutils/InetAddressMockery.java [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+     * 
+     * @param hostname The hostname.
+     * @param ip4Address The IPv4 address (e.g. {@code 0x01020304})
+     * @return The Inet4Address object.
+     * @throws IllegalStateException on internal error.
+     */
+    public static InetAddress mockedResolvedIPv4Address(String hostname, int ip4Address) {
+        try (ObjectInputStream in = new ObjectInputStream(new ByteArrayInputStream(serializeIp4(hostname,
+                ip4Address)))) {
+            return (InetAddress) in.readObject();
```
Comment (kofemann) [inline core/src/test/java/org/dcache/testutils/InetAddressMockery.java:54]: what about just use standard `InetAddress.html#getByAddress(java.lang.String,byte[])`?

**Review by kofemann — CHANGES_REQUESTED** [review]
Thanks for looking at this. The proposed solution seems overengineered. Please consider an alternative approach.

File: core/src/test/java/org/dcache/testutils/InetAddressMockery.java (hunk 1 above)
Comment (kohlschuetter) [reply core/src/test/java/org/dcache/testutils/InetAddressMockery.java]: Absolutely. I didn't think too hard when copying code from another project. Thanks for the reminder!

**Comment by kofemann** [comment]
Thanks for the contribution 🚀
